### ISSUE TITLE
Use auth token instead of hashing email+pw

### ISSUE THREAD

**Issue by pjo336** [nxttmac/roloduck#7]
Should it be done?

**Comment by nxttmac** [comment]
What does that mean?

On Wednesday, January 29, 2014, pjo336 notifications@github.com wrote:

> Should it be done?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/nxttmac/roloduck/issues/7
> .

## 

Andrew Ertell

a.ertell@gmail.com
323.206.6263
